export * from "./About"
export * from "./Contact"
export * from "./Games"
export * from "./Home"
export * from "./ScoreBoard"
export * from "./signup/Signup"
export * from "./login/Login"
export * from "./tetrisGame/TetrisPage"